### ISSUE TITLE
No function pred_linearize

### ISSUE THREAD

**Issue by fanyou12** [DoodleJZ/HPSG-Neural-Parser#4]
Loading model from models/joint_bert_dev=95.55_devuas=96.67_devlas=94.86.pt1...
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
packages/torch/nn/_reduction.py:49: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Parsing sentences...
Traceback (most recent call last):
  File "src_joint/main.py", line 746, in <module>
    main()
  File "src_joint/main.py", line 742, in main
    args.callback(args)
  File "src_joint/main.py", line 680, in run_parse
    save_data(syntree_pred, cun)
  File "src_joint/main.py", line 651, in save_data
    output_file.write("{}\n".format(tree.pred_linearize()))
AttributeError: 'InternalParseNode' object has no attribute 'pred_linearize'

**Comment by yunju63** [comment]
I have the same problem like below..!

<img width="703" alt="스크린샷 2020-01-27 오전 1 07 15" src="https://user-images.githubusercontent.com/44551410/73138016-5d73bd80-40a1-11ea-8459-5644469cede7.png">

**Comment by magoafono** [comment]
Me too!

**Comment by sanjeetGupta** [comment]
Try tho change:   "tree.linearize()" to  "tree.convert().linearize()"

**Comment by magoafono** [comment]
> Try tho change: "tree.linearize()" to "tree.convert().linearize()"

Thank you! The problem is solved for me.
